[workspace]
resolver = "2"
members = ["crates/colorimetrie", "crates/fdx-sys", "crates/fd9-sys", "crates/pont-protocole", "crates/pont-myiro1", "crates/pont-fd9", "crates/jeu-validation", "crates/bibliotheque", "app"]

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/entropik/myiro-libre"
